language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

cache:
    - apt
    - pip

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y liblo7
    - sudo apt-get install -y liblo-dev
    - pip install --user Cython
    - pip install --user -r requirements.txt

# command to install dependencies
install:
    - "pip install ."

# command to run tests
script: py.test
