language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblo7
  - sudo apt-get install -y liblo-dev

# command to install dependencies
install:
  - "pip install ."
  - "pip install pyliblo"
  - "pip install pymodbus"
# command to run tests
script: py.test
